name: xKit
main: com.mengcraft.xkit.Main
version: ${project.version}

commands:
  xkit:
    description: None.
    permission: xkit.use
    
permissions:
  xkit.admin:
    description: None.
    default: op
  xkit.use:
    description: None.
    default: true

depend: [ProtocolLib, SimpleORM]
softdepend: [PlaceholderAPI]
